name: Handle Dependabot PRs

on:
  pull_request:
    branches:
      - 'dependabot/**'  # Match only PRs created from Dependabot branches
    types: [opened, synchronize, labeled]

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack-channel: "dependabot-alerts"  # e.g., "#dependabot-alerts"
          slack-text: "New Dependabot PR opened in *${{ github.repository }}*:\n<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"

      - name: Close PR if checks fail
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const checks = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.data.head.sha
            });

            const anyFailed = checks.data.check_runs.some(c => c.conclusion === 'failure');

            if (anyFailed) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.data.number,
                state: 'closed'
              });

              console.log('PR closed due to failed checks.');
            } else {
              console.log('All checks passed.');
            }
