name: Notify on PR Open

on:
  pull_request:
    types: [opened]

jobs:
  slack-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "📢 New PR opened in ${{ github.repository }}",
              "username": "PR Notifier",
              "icon_emoji": ":bell:",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*<${{
                      github.event.pull_request.html_url
                    }}|New PR opened in ${{ github.repository }}>*\n*Title:* ${{ github.event.pull_request.title }}\n*Number:* #${{ github.event.pull_request.number }}\n*Author:* <${{ github.event.pull_request.user.html_url }}|@${{ github.event.pull_request.user.login }}>"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View PR",
                        "emoji": true
                      },
                      "url": "${{ github.event.pull_request.html_url }}"
                    }
                  ]
                }
              ]
            }
