name: Dependabot Slack Notifications

on:
  workflow_dispatch:
    inputs:
      pr_title:
        description: 'PR Title'
        required: false
        default: '[Manual trigger - no PR title]'
      pr_link:
        description: 'PR Link'
        required: false
        default: '[Manual trigger - no PR link]'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": " *PR Open*: <https://github.com/${{ github.repository }}|${{ github.repository }}>"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Title*\n${{ inputs.pr_title || github.event.pull_request.title || '[No title provided]' }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*\n${{ github.actor || github.event.pull_request.user.login || '[Unknown author]' }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Link*\n${{ inputs.pr_link || github.event.pull_request.html_url || '[No link available]' }}"
                  }
                }
              ]
            }
