name: PR Checks Completed Notification

on:
  status:
    types: [completed]

jobs:
  notify-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare PR Link
        id: prepare-link
        run: |
          if [ "${{ github.event.check_suite.pull_requests[0].html_url }}" != "" ]; then
            echo "PR_LINK=${{ github.event.check_suite.pull_requests[0].html_url }}" >> $GITHUB_ENV
          else
            echo "PR_LINK=https://github.com/${{ github.repository }}/pulls" >> $GITHUB_ENV
          fi

      - name: Send Slack Notification for Success
        if: github.event.check_suite.conclusion == 'success'
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": ":white_check_mark: PR checks passed in ${{ github.repository }}\nTitle: ${{ github.event.check_suite.pull_requests[0].title || 'Unknown' }}\nAuthor: ${{ github.event.check_suite.pull_requests[0].user.login || github.actor }}\nLink: ${{ env.PR_LINK }}",
              "username": "Dependabot Manager",
              "icon_emoji": ":robot_face:"
            }

      - name: Send Slack Notification for Failure
        if: github.event.check_suite.conclusion == 'failure'
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": ":x: PR checks failed in ${{ github.repository }}\nTitle: ${{ github.event.check_suite.pull_requests[0].title || 'Unknown' }}\nAuthor: ${{ github.event.check_suite.pull_requests[0].user.login || github.actor }}\nLink: ${{ env.PR_LINK }}",
              "username": "Dependabot Manager",
              "icon_emoji": ":robot_face:"
            }
