name: Handle Completed Dependabot PR Checks

on:
  check_suite:
    types: [completed]

jobs:
  handle_dependabot_checks:
    if: >
      github.event.check_suite.pull_requests != null &&
      github.event.check_suite.pull_requests[0].user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Extract PR Info
        id: pr_info
        run: |
          echo "PR_NUMBER=$(jq '.[0].number' <<< '${{ toJson(github.event.check_suite.pull_requests) }}')" >> $GITHUB_ENV
          echo "PR_TITLE=$(jq -r '.[0].title' <<< '${{ toJson(github.event.check_suite.pull_requests) }}')" >> $GITHUB_ENV
          echo "PR_URL=$(jq -r '.[0].html_url' <<< '${{ toJson(github.event.check_suite.pull_requests) }}')" >> $GITHUB_ENV

      - name: Close PR if checks failed
        if: ${{ github.event.check_suite.conclusion != 'success' }}
        uses: superbrothers/close-pull-request@v3
        with:
          pull-request-number: ${{ env.PR_NUMBER }}
          comment: "Closed automatically due to failed checks."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Slack - PR Success
        if: ${{ github.event.check_suite.conclusion == 'success' }}
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": ":white_check_mark: Dependabot PR #${{ env.PR_NUMBER }} passed all checks.",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Successful PR:* <${{ env.PR_URL }}|${{ env.PR_TITLE }}> passed all CI checks."
                  }
                }
              ]
            }
