name: Dependabot Slack Notifications

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "🚀 *New Dependabot PR*",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rocket: *New Dependabot PR*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*PR Title:*\n<https://github.com/${{ github.repository }}/pull/123|Bump lodash from 4.17.15 to 4.17.21>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\nmain"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*PR Number:*\n#123"
                    }
                  ]
                }
              ]
            }
