name: Test Dependabot Slack Alert

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message to Slack
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          slack-message: "TEST: Manual workflow triggered in *${{ github.repository }}*"
