name: Dependabot PR Manager

on:
  check_suite:
    types: [completed]

jobs:
  monitor_checks:
    if: github.event.action == 'completed' && github.event.check_suite.conclusion != 'neutral'
    runs-on: ubuntu-latest

    steps:
      - name: Get associated PR
        id: get_pr
        uses: actions/github-script@v6
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.payload.check_suite.head_branch,
              state: 'open'
            });
            const dependabotPR = prs.data.find(pr => pr.user.login === 'dependabot[bot]');
            if (dependabotPR) {
              core.setOutput('pr_number', dependabotPR.number);
              core.setOutput('pr_title', dependabotPR.title);
              core.setOutput('pr_url', dependabotPR.html_url);
            }

      - name: Close PR if checks failed
        if: github.event.check_suite.conclusion != 'success' && steps.get_pr.outputs.pr_number != ''
        uses: superbrothers/close-pull-request@v3
        with:
          pull-request-number: ${{ steps.get_pr.outputs.pr_number }}
          comment: "Automatically closed due to failed checks"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Slack if checks passed
        if: github.event.check_suite.conclusion == 'success' && steps.get_pr.outputs.pr_number != ''
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "✅ Dependabot PR #${{ steps.get_pr.outputs.pr_number }} passed all checks in ${{ github.repository }}",
              "username": "Dependabot Manager",
              "icon_emoji": ":white_check_mark:",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":white_check_mark: Dependabot PR Passed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*PR Number*\n#${{ steps.get_pr.outputs.pr_number }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Title*\n${{ steps.get_pr.outputs.pr_title }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR Link*\n<${{ steps.get_pr.outputs.pr_url }}|View PR>"
                  }
                }
              ]
            }
