name: Dependabot PR Notifier

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare PR Link
        id: prepare-link
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "PR_LINK=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          else
            echo "PR_LINK=https://github.com/${{ github.repository }}/pulls" >> $GITHUB_ENV
          fi

      - name: Send PR notification
        if: github.event.action == 'opened' || github.event_name == 'workflow_dispatch'
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "📦 New PR in ${{ github.repository }}\nTitle: ${{ github.event.pull_request.title || 'Manual trigger' }}\nAuthor: ${{ github.event.pull_request.user.login || github.actor }}\nLink: ${{ env.PR_LINK }}",
              "username": "Dependabot Manager",
              "icon_emoji": ":robot_face:"
            }

      - name: Send closed PR notification
        if: github.event.action == 'closed'
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "❌ PR Closed in ${{ github.repository }}\nTitle: ${{ github.event.pull_request.title }}\nAuthor: ${{ github.event.pull_request.user.login }}\nLink: ${{ github.event.pull_request.html_url }}\nStatus: ${{ github.event.pull_request.merged ? 'Merged' : 'Closed without merge' }}",
              "username": "Dependabot Manager",
              "icon_emoji": ":warning:"
            }
