name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest] # windows-latest, macos-latest
        dotnet: ['2.0', '2.1', '2.2', '3.0', '3.1', '5.0', '6.0']
    name: Dotnet ${{ matrix.dotnet }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: "! contains(toJSON(github.event.head_commit.message), 'skip ci')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test
