name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04] # windows-latest, macos-latest
        dotnet: ['2.0.x', '2.1.x', '2.2.x', '3.0.x', '3.1.x', '5.0.x', '6.0.x', '7.0.x']
    name: Dotnet ${{ matrix.dotnet }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: "! contains(toJSON(github.event.head_commit.message), 'skip test')"
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build
      run: dotnet build

    - name: Test
      if: ${{ matrix.os != 'ubuntu-22.04' || matrix.dotnet != '7.0.x' }}
      run: dotnet test

    - name: Test & Coverage Collection
      if: ${{ matrix.os == 'ubuntu-22.04' && matrix.dotnet == '7.0.x' }}
      run: dotnet test APIMatic.Core.Test/APIMatic.Core.Test.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

    - name: SonarQube Scan
      if: ${{ github.actor != 'dependabot[bot]' && matrix.os == 'ubuntu-22.04' && matrix.dotnet == '7.0.x' }}
      uses: SonarSource/sonarqube-scan-action@v5.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
